environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '9'
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run test
build: off
matrix:
  fast_finish: true
